{"name": "Successful User Login", "status": "broken", "statusDetails": {"message": "KeyError: 'account_page'", "trace": "pages = {'admin_page': <pages.admin.AdminPage object at 0x0000022FAA1FA660>, 'cart_page': <pages.cart.CartPage object at 0x000...s.home.HomePage object at 0x0000022FAA1F8EC0>, 'login_page': <pages.login.LoginPage object at 0x0000022FAA1FA510>, ...}\n\n    @allure.feature(\"Authentication\")\n    @allure.title(\"Successful User Login\")\n    def test_login(pages):\n        \"\"\"Test successful user login with valid credentials\"\"\"\n        home_page = pages[\"home_page\"]\n        login_page = pages[\"login_page\"]\n>       account_page = pages[\"account_page\"]\n                       ^^^^^^^^^^^^^^^^^^^^^\nE       KeyError: 'account_page'\n\nkt4.py:19: KeyError"}, "description": "Test successful user login with valid credentials", "attachments": [{"name": "screenshot_on_failure", "source": "6c83d313-4e71-450c-a3d0-4b82f70cf4f5-attachment.png", "type": "image/png"}], "start": 1749400986936, "stop": 1749400986936, "uuid": "338216cf-0c49-4fda-ae5d-8c2c8d354711", "historyId": "bd968de1114ae6826f17e92fcfe0eed0", "testCaseId": "bd968de1114ae6826f17e92fcfe0eed0", "fullName": "kt4#test_login", "labels": [{"name": "feature", "value": "Authentication"}, {"name": "suite", "value": "kt4"}, {"name": "host", "value": "DESKTOP-FQ1L8FN"}, {"name": "thread", "value": "13668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "kt4"}]}