{"uuid": "a70a1747-0c51-4c56-86f8-0a9fe1a483d1", "children": ["45f8180c-2c99-4ae6-bd3a-c2fb5e7b48bf"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"d:\\Documents\\katya\\tasks\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"d:\\Documents\\katya\\tasks\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"d:\\Documents\\katya\\tasks\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"d:\\Documents\\katya\\tasks\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\Documents\\katya\\tasks\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\Documents\\katya\\tasks\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Documents\\katya\\tasks\\Study_Tests-main\\conftest.py\", line 44, in driver\n    driver = webdriver.Chrome(options=options)\n  File \"d:\\Documents\\katya\\tasks\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 47, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        browser_name=DesiredCapabilities.CHROME[\"browserName\"],\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        keep_alive=keep_alive,\n        ^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"d:\\Documents\\katya\\tasks\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 58, in __init__\n    self.service.start()\n    ~~~~~~~~~~~~~~~~~~^^\n  File \"d:\\Documents\\katya\\tasks\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 107, in start\n    if self.is_connectable():\n       ~~~~~~~~~~~~~~~~~~~^^\n  File \"d:\\Documents\\katya\\tasks\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 124, in is_connectable\n    return utils.is_connectable(self.port)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"d:\\Documents\\katya\\tasks\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 98, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n  File \"C:\\Users\\polag\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\socket.py\", line 856, in create_connection\n    exceptions.clear()  # raise only the last error\n    ~~~~~~~~~~~~~~~~^^\n"}, "start": 1749398664754, "stop": 1749398665833}], "start": 1749398664754, "stop": 1749398666288}